name: Conduit Deployment

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - cicd-actions-build
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repository
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      # 2. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build & push backend image
      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./conduit-backend
          file: ./conduit-backend/Dockerfile
          push: true
          tags: ghcr.io/bodev13/conduit-backend:latest
            ghcr.io/bodev13/conduit-backend:${{ github.sha }}
          build-args: |
            ENV_FILE=.env

      # 5. Build & push frontend image
      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./conduit-frontend
          file: ./conduit-frontend/Dockerfile
          push: true
          tags: ghcr.io/bodev13/conduit-frontend:latest
            ghcr.io/bodev13/conduit-frontend:${{ github.sha }}
          build-args: |
            ENV_FILE=.env

      # 6. Deploy to Cloud VM (only pull + up -d)
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.SERVER_USER }}/conduit-fullstack-app
            git pull origin cicd-actions-build
            git submodule update --init --recursive
            docker compose pull
            docker compose up -d
