name: Conduit Deployment

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - cicd-actions-build
      - main
   workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repository
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      # 2. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build & push backend image
      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./conduit-backend
          file: ./conduit-backend/Dockerfile
          push: true
          tags: |
            ghcr.io/bodev13/conduit-backend:latest
            ghcr.io/bodev13/conduit-backend:${{ github.sha }}
          build-args: |
            ENV_FILE=.env

      # 5. Build & push frontend image
      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./conduit-frontend
          file: ./conduit-frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/bodev13/conduit-frontend:latest
            ghcr.io/bodev13/conduit-frontend:${{ github.sha }}
          build-args: |
            ENV_FILE=.env

      # 6. Preparation of .env file
      - name: Prepare env file
        run: |
          cat <<EOF > env.prod
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=${{ secrets.DEBUG }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
          API_URL=${{ secrets.API_URL }}
          EOF

      # 7. Upload docker-compose.yml and .env to server
      - name: Upload deployment files
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose.yml, env.prod
          target: /home/${{ secrets.SERVER_USER }}/conduit-fullstack-app

      # 8. Deploy to Cloud VM (only pull + up -d)
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/conduit-fullstack-app
            mv env.prod .env
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker compose pull
            docker image prune -f
            docker compose --env-file .env up -d --remove-orphans
