name: Conduit Deployment

on:
  push:
    branches:
      - cicd-setup # branch to push the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repository with submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Deploy & build directly on Cloud VM
      - name: Deploy to Cloud VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            # Going to the project directory on cloud VM
            cd /home/${{ secrets.SERVER_USER }}/conduit-fullstack-app
            git pull origin cicd-setup
            git submodule update --init --recursive
            docker-compose down
            docker-compose up -d --build
