name: Conduit Deployment

on:
  push:
    branches:
      - cicd-setup # branch to push the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloning repository together with submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build and push of backend
      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./conduit-backend
          file: ./conduit-backend/Dockerfile
          push: true
          tags: ghcr.io/bodev13/conduit-backend:latest
          build-args: |
            ENV_FILE=.env

      # 5. Build and push of frontend
      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./conduit-frontend
          file: ./conduit-frontend/Dockerfile
          push: true
          tags: ghcr.io/bodev13/conduit-frontend:latest
          build-args: |
            ENV_FILE=.env

      # 6. Deploy to Cloud VM
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.SERVER_USER }}/conduit-fullstack-app
            docker-compose down
            docker-compose up -d
